### ISSUE TITLE
Values are being retained, but input_numbers no longer work (sliders)

### ISSUE THREAD

**Issue by krasatos** [gazoscalvertos/HASS-Persistence#3]
Hey, 
Thanks for this component, it's something that HA really misses.
(at least i cant get restore_state to work)

I have enabled your component on several input_number entities,
After restart the values are retained but they no longer react as sliders.
There is no line to drag next to them, and in the states page, i get the name and state correct, but blank attributes.

Here is the sensor i have enabeld:
```
 - platform: persistence
    entities:
       - input_number.irrigation_routine_1_start_hour
       - input_number.irrigation_routine_1_zone_1_min
       - input_number.irrigation_routine_1_zone_2_min
       - input_number.irrigation_routine_1_zone_3_min
       - input_number.irrigation_routine_1_zone_4_min
       - input_number.irrigation_routine_1_zone_5_min
```
And sample of my input_number code:
```
  irrigation_routine_1_zone_1_min:
    name: Zone 1 Timer
    initial: 0
    min: 0
    max: 20
    step: 1
    unit_of_measurement: m
    mode: slider
    icon: mdi:timer
    
```

ANy ideas?
Thanks in advance
