### ISSUE TITLE
Error doing job: Future exception was never retrieved

### ISSUE THREAD

**Issue by Frankster-NL** [gazoscalvertos/HASS-Persistence#4]
After implementing hass-persistence I continuously get errors like the one below:
```Log Details (ERROR)

Sun May 20 2018 07:26:55 GMT+0200 (W. Europe Daylight Time)

Error doing job: Future exception was never retrieved

Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/.homeassistant/custom_components/sensor/persistence.py", line 99, in state_change_listener
    self._persistence_list[event.data['entity_id']] = event.data.get('new_state', None).state
TypeError: list indices must be integers or slices, not str
```

Running Home-assistant 0.69.0

Relevant configurtation.yaml:
```
sensor:
  - platform: persistence
    entities: #ADD ALL OF YOUR ENTITIES HERE
      - counter.doorbell_counter
      - counter.dryer_counter
      - counter.frankaway_counter
      - counter.jetaway
      - counter.toilet_counter
      - counter.washmachine_counter
      - light.badkamer_lamp
      - light.badkamer_spiegel
      - light.bank_licht
      - light.eettafel
      - light.gang
      - light.gang_boven
      - light.gang_zolder
      - light.keuken
      - light.kledingkamer
      - light.lieke_grote_lamp
      - light.lieke_kleine_lamp
      - light.rommelhok
      - light.schuur_binnenverlichting
      - light.schuur_buitenverlichting
      - light.slaapkamer_frank_en_jet
      - light.toilet
      - light.tv_licht
      - light.wasmachinehok
      - light.werkkamer_lamp
      - light.werkkamer_spots
      - light.yeelight_rgb_7811dc6ba370
      - sensor.boiler_mean
      - sensor.boilerdaily_mean
      - sensor.dryer_mean
      - sensor.dryerdaily_mean
      - sensor.gas_consumption
      - sensor.hourly_gas_consumption
      - sensor.mqttdailykwhboiler
      - sensor.mqttdailykwhdryer
      - sensor.mqttdailykwhtotal
      - sensor.mqttdailykwhtv
      - sensor.mqttdailykwhwashing_machine
      - sensor.mqtthourlykwhboiler
      - sensor.mqtthourlykwhdryer
      - sensor.mqtthourlykwhtotal
      - sensor.mqtthourlykwhtv
      - sensor.mqtthourlykwhwashing_machine
      - sensor.total_mean
      - sensor.totaldaily_mean
      - sensor.tv_mean
      - sensor.tvdaily_mean
      - sensor.washing_machine_mean
      - sensor.washing_machinedaily_mean
```
